#!/bin/sh

echo "run test pre push"

git reset HEAD .
count=`git diff|wc -l`

echo ${count}

if [ ${count} != 0 ];then
    echo "Stashing local changes"
    git stash
    echo "Running tests"
fi

go test ./...
#
# $? stores exit value of the last command
FAIL=$?

echo ${FAIL}

if [ ${count} != 0 ];then
    echo "Recovering local changes"
    git stash pop
fi

if [ $FAIL != 0 ]; then
    echo "Tests must pass before push!"
    exit 1
fi

echo "diff count: ${count}"
